#' Compute a statistical transformation
#'
#' @param params A parameter object generated by of the other functions in
#'    this packagea
#' @param x X position. This is required by all stats. \code{y}, \code{z},
#'    and \code{w} should always be the same length as \code{x}.
#' @param y Y position. This is required by all 2d stats.
#' @param z Z value. This is required by all stats that compute a summary.
#' @param w Weights. Optional vector of weights.
#' @export
compute_stat <- function(params, x, y, z, w = NULL) {
  UseMethod("compute_stat")
}
