#' Compute a statistical transformation
#'
#' @param params A parameter object generated by of the other functions in
#'    this packagea
#' @param x X position. This is required by all stats. \code{y}, \code{z},
#'    and \code{w} should always be the same length as \code{x}.
#' @param ... Additional arguments passed on to stat. Many stats take
#'    \code{y} and \code{z} values.
#' @param w Weights. Optional vector of weights.
#' @export
compute_stat <- function(params, x, ..., w = NULL) {
  UseMethod("compute_stat")
}
